### ISSUE TITLE
SEED download

### ISSUE THREAD

**Issue by Junonia** [MG-RAST/myM5NR#20]
Trying to construct a local version of M5NR, but I was not able to complete the download of SEED.  The download using querySAS.pl always get terminated before it finishes and the lftp directory pointed by the script was not there any more.   Any other alternative download methods?

**Comment by wltrimbl** [comment]
It appears that the directory on the SEED ftp site has been removed.  It was used here only to get a version number.  We have updated the code and replaced the version number with the current date.
